apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scan-settings
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/mike4263/scan-settings.git
    targetRevision: HEAD
    path: infrastructure/
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-compliance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
