kind: ScanSetting
apiVersion: compliance.openshift.io/v1alpha1
autoApplyRemediations: false
debug: true
metadata:
  name: custom
  namespace: openshift-compliance
rawResultStorage:
  rotation: 10
  size: 2Gi
roles:
  - worker
  - master
schedule: 0 1 * * *

